module.exports = {
  name: 'ajay-sko',

  slides: [
    "cover.html",
    "slide-02.html",
    "slide-03.html",
    "slide-04.html",
    "slide-05.html",
    "slide-06.html",
    "slide-07.html",
    "slide-08.html",
    "slide-09.html",
    "slide-10.html",
    "slide-11.html",
    "slide-12.html",
    "slide-13.html",
    "slide-14.html",
    "slide-15.html",
    "slide-16.html",
    "slide-17.html",
    "slide-18.html",
    "slide-19.html",
    "slide-20.html",
    "slide-21.html",
    "slide-22.html",
    "slide-23.html",
    "thank-you.html",
  ],

  labels: [
    "Cover: Do less with Serverless",
    "Serverless is the fastest path to solution at scale",
    "WHY: Stop selling infrastructure and start selling velocity",
    "A choice to match every customer's needs",
    "Self-Managed vs Hosted vs Serverless",
    "Celebrate Serverless - Acknowledge the journey!",
    "Winning today with Serverless",
    "WHAT: Spot, listen, solve, deliver value, sell",
    "Net-new VS existing customers",
    "The Unhappy Operator – GoDaddy",
    "The Variable Workload Consumer – Guidewire",
    "The Platform Innovator – kore.ai",
    "The SaaS Defensive Overlay",
    "Optimizing for Customer Value",
    "HOW: Your toolset for success",
    "Do less infrastructure, deliver more outcomes",
    "We've got you covered",
    "Lead with Serverless, win on Marketplaces",
    "The Marketplace Opportunity",
    "Incentives for YOU & Your Customers",
    "FY27 - The year of Serverless",
    "Start Now!",
    "Stop selling infrastructure and start selling velocity",
    "Thank you",
  ],
};
